# docker-compose.yml
version: '3.8'

services:
  db:
    build: .
    environment:
      POSTGRES_DB: dog_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
